CREATE OR REPLACE FUNCTION FOBTMANAPARA(P_MAID IN VARCHAR2,P_MANO IN VARCHAR2) RETURN VARCHAR2 AS
   V_RET VARCHAR2(1000);
BEGIN
  --获取架构参数
  SELECT CONTENT
    INTO V_RET
    FROM BAS_MANA_PARA
   WHERE MANAGE_NO = P_MAID
     AND PARAMETER_NO = P_MANO;
  RETURN V_RET;
EXCEPTION
  WHEN OTHERS THEN
    RETURN '';
END;
/

