CREATE OR REPLACE PROCEDURE HRBZLS."DAY_RPT_TM" IS
  V_MONTH VARCHAR2(10);
BEGIN
  /**此处是否为自然月份？**/
  SELECT TO_CHAR(SYSDATE, 'yyyy.mm') INTO V_MONTH FROM DUAL;
  PG_EWIDE_REPORTSUM_LYG_01.综合月报(V_MONTH);
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

