CREATE OR REPLACE FUNCTION HRBZLS.F_CHR9(P_STR IN VARCHAR2)
RETURN VARCHAR2 AS
  V_TMP VARCHAR2(4000);
BEGIN
  V_TMP:=REPLACE(P_STR,CHR(9));
  V_TMP:=REPLACE(V_TMP,CHR(3),CHR(9));
  RETURN V_TMP;
END F_CHR9;
/

