CREATE OR REPLACE FUNCTION HRBZLS."FBFJCBM"
 (TCODE IN CHAR,TCLASS IN NUMBER)
 RETURN CHAR
 AS
 LCODE VARCHAR2(10);
 BEGIN
 SELECT BFID INTO LCODE FROM BOOKFRAME WHERE BFCLASS=TCLASS
 START WITH BFID=TCODE CONNECT BY PRIOR BFPID=BFID;
 RETURN LCODE;
 EXCEPTION WHEN OTHERS THEN
 LCODE := TCODE;
 RETURN LCODE;
 END FBFJCBM;
/

