CREATE OR REPLACE FUNCTION HRBZLS.FCHECKIFDZ(P_MID IN VARCHAR2) RETURN VARCHAR2 IS
  RESULT VARCHAR2(10);
  N      NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO N
    FROM METERTGL
   WHERE MTMID = P_MID
     AND MTSTATUS = 'Y'
     AND MTTGL > 0;
  IF N = 1 THEN
    RESULT := 'Y';
  ELSE
    RESULT := 'N';
  END IF;
  RETURN(RESULT);
END FCHECKIFDZ;
/

