CREATE OR REPLACE FUNCTION HRBZLS."FFORMATTOCHAR"(P_NUM IN NUMBER) RETURN VARCHAR2 IS
  V_RET VARCHAR2(100);
BEGIN
  IF TRUNC(P_NUM) <> P_NUM THEN
    --有小数位
    V_RET := TO_CHAR(P_NUM, 'FM999999990.9999');
  ELSE
    --无小数位
    V_RET := TO_CHAR(P_NUM);
  END IF;
  RETURN V_RET;
EXCEPTION
  WHEN OTHERS THEN
    RETURN TO_CHAR(P_NUM);
END FFORMATTOCHAR;
/

