CREATE OR REPLACE FUNCTION HRBZLS."FGETBFRPERTEL_SMFID" (P_BFID IN VARCHAR2,p_bfsmfid in varchar2) RETURN VARCHAR2 AS
  LRET VARCHAR2(60);
BEGIN
  SELECT oatel  INTO LRET FROM BOOKFRAME,operaccnt WHERE
   BFID = P_BFID and BFRPER=oaid
  and bfsmfid=p_bfsmfid;
  RETURN LRET;
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;
/

