CREATE OR REPLACE FUNCTION HRBZLS."FGETSYSMANAPARAVALUE" (P_SMFID IN VARCHAR2,P_SMPPID IN VARCHAR2)
 RETURN VARCHAR2
AS
 LRET VARCHAR2(400);
BEGIN
SELECT SMPPVALUE INTO LRET FROM SYSMANAPARA T WHERE SMPPID=P_SMPPID AND SMPID=P_SMFID;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

