CREATE OR REPLACE FUNCTION HRBZLS."FGETMAXROLE" (P_PER IN VARCHAR2) RETURN VARCHAR2 IS
  V_RET VARCHAR2(10);
BEGIN
  SELECT T.OARRID
    INTO V_RET
    FROM OPERACCNTROLE T
   WHERE T.OAROAID = P_PER
     AND FGETOROLECLASS(OARRID) =
         (SELECT MIN(FGETOROLECLASS(OARRID)) CLASS
            FROM OPERACCNTROLE T
           WHERE T.OAROAID = P_PER)
     AND ROWNUM < 2;
  RETURN V_RET;
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;
/

