CREATE OR REPLACE FUNCTION HRBZLS."FGETBILLMAIN" (P_BMTYPE IN VARCHAR2,P_COLNAME IN VARCHAR2 )
 RETURN VARCHAR2
AS
 BM BILLMAIN%ROWTYPE;
 V_RET VARCHAR2(20000);
BEGIN
 SELECT *
 INTO BM
 FROM BILLMAIN
 WHERE BMTYPE = P_BMTYPE ;
 IF P_COLNAME='BMFLAG1' THEN
    execute immediate BM.BMFLAG1 into V_RET;
    RETURN   V_RET  ;
 END IF;
 IF P_COLNAME='BMFLAG2' THEN
        execute immediate BM.BMFLAG2 into V_RET;
    RETURN   V_RET  ;
 END IF;
  IF P_COLNAME='BMFLAG3' THEN
        execute immediate BM.BMFLAG3 into V_RET;
    RETURN   V_RET  ;
 END IF;
  IF P_COLNAME='BMFLAG4' THEN
        execute immediate BM.BMFLAG4 into V_RET;
    RETURN   V_RET  ;
 END IF;
  IF P_COLNAME='BMFLAG5' THEN
        execute immediate BM.BMFLAG5 into V_RET;
    RETURN   V_RET  ;
 END IF;
  IF P_COLNAME='BMFLAG6' THEN
        execute immediate BM.BMFLAG6 into V_RET;
    RETURN   V_RET  ;
 END IF;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

