CREATE OR REPLACE FUNCTION HRBZLS.FGETOPERFUNCDATE1(VOAID IN VARCHAR2,
                                            VFID  IN VARCHAR2) RETURN DATE AS
  LDATE DATE;
BEGIN
  SELECT ORFSTARTDATE
    INTO LDATE
    FROM OPERACCNTROLEFUNC_EX
   WHERE ORFOAID = VOAID
     AND ORFFID = VFID;
  RETURN LDATE;
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;
/

