CREATE OR REPLACE FUNCTION HRBZLS."FGETMETERCABILER" (P_MMID IN VARCHAR2 )
 RETURN VARCHAR2
AS
 LRET VARCHAR2(20);
BEGIN
 SELECT MDCALIBER
 INTO LRET
 FROM METERDOC
 WHERE MDMID = P_MMID;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

