CREATE OR REPLACE FUNCTION HRBZLS."FGETPWPRICE" (P_MCODE IN VARCHAR2) RETURN NUMBER
 AS
  P_PFPRICE NUMBER(12, 2);
BEGIN
  SELECT SUM(PDDJ)
  INTO P_PFPRICE
  FROM METERINFO, PRICEDETAIL
 WHERE MIPFID = PDPFID
   AND PDPIID = '02'
   AND MICODE = P_MCODE;
  RETURN P_PFPRICE;
EXCEPTION WHEN OTHERS THEN
  RETURN NULL;
END;
/

