CREATE OR REPLACE FUNCTION HRBZLS."FGETENTRUSTTASK_ETCYCLEDAYS" (P_ETBNAKID IN VARCHAR2 )
 RETURN NUMBER
AS
 V_ETCYCLEDAYS ENTRUSTTASK.ETCYCLEDAYS%TYPE;

BEGIN
 SELECT ETCYCLEDAYS
 INTO V_ETCYCLEDAYS
 FROM ENTRUSTTASK
 WHERE ETBNAKID = P_ETBNAKID;
 RETURN V_ETCYCLEDAYS;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

