CREATE OR REPLACE FUNCTION HRBZLS."FGETFINALPRICENAME"(P_PFID IN VARCHAR2)
  RETURN VARCHAR2 AS
  LRET VARCHAR2(500);
  RRET VARCHAR2(500);
BEGIN
  SELECT PFNAME INTO LRET FROM PRICEFRAME WHERE PFID = P_PFID;
  --取最末级水价中文名
  SELECT SUBSTR(LRET, INSTR(LRET, '/', -1, 1) + 1, LENGTH(LRET)) INTO RRET FROM DUAL;
  RETURN RRET;
EXCEPTION
  WHEN OTHERS THEN
    RETURN P_PFID;
END;
/

