CREATE OR REPLACE FUNCTION HRBZLS."FGETSYSREADTYPE" (P_SRTID IN VARCHAR2)
 RETURN VARCHAR2
AS
 LRET CHAR(20);
BEGIN
 SELECT SRTNAME
 INTO LRET
 FROM SYSREADTYPE
 WHERE SRTID = P_SRTID;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

