CREATE OR REPLACE FUNCTION HRBZLS."FGETREADPRICE" (P_PID VARCHAR2) RETURN NUMBER AS
  V_RET READPRICE.RPPRICE%TYPE;
BEGIN
  SELECT RPPRICE INTO V_RET FROM READPRICE WHERE RPID = P_PID;
  RETURN V_RET;
EXCEPTION
  WHEN OTHERS THEN
    RETURN 1;
END;
/

