CREATE OR REPLACE FUNCTION HRBZLS."FGETBFRPER_SMFID" (P_BFID IN VARCHAR2,p_bfsmfid in varchar2) RETURN VARCHAR2 AS
  LRET VARCHAR2(60);
BEGIN
  SELECT fgetopername(BFRPER) INTO LRET FROM BOOKFRAME WHERE BFID = P_BFID
  and bfsmfid=p_bfsmfid;
  RETURN LRET;
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;
/

