CREATE OR REPLACE FUNCTION HRBZLS."FGETMETERTYPE" (P_SMTID IN VARCHAR2 )
 RETURN VARCHAR2
AS
 LRET VARCHAR2(20);
BEGIN
 SELECT SMTNAME
 INTO LRET
 FROM sysmetertype
 WHERE SMTID = P_SMTID;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

