CREATE OR REPLACE FUNCTION HRBZLS."FGETINVOICETYPE" (P_ITID IN VARCHAR2 )
 RETURN VARCHAR2
AS
 LRET VARCHAR2(20);
BEGIN
 SELECT ITNAME
 INTO LRET
 FROM INVOICETYPE
 WHERE ITID = P_ITID;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

