CREATE OR REPLACE FUNCTION HRBZLS."FGETMETERSIDE" (P_SIDE IN VARCHAR2 )
 RETURN VARCHAR2
AS
 LRET VARCHAR2(20);
BEGIN
 SELECT SCLVALUE
 INTO LRET
 FROM syscharlist t
 WHERE T.SCLTYPE=' ±íÎ»' AND SCLID = P_SIDE;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

