CREATE OR REPLACE FUNCTION HRBZLS."FGETIFDZSB"(P_CODE IN VARCHAR2) RETURN VARCHAR2 AS
  LRET VARCHAR2(40);
BEGIN
  SELECT NVL(IFDZSB, 'N') INTO LRET FROM METERDOC WHERE MDMID = P_CODE;
  RETURN LRET;
EXCEPTION
  WHEN OTHERS THEN
    RETURN 'N';
END;
/

