CREATE OR REPLACE FUNCTION HRBZLS."FGETPRICEFRAME" (P_PFID IN VARCHAR2)
  RETURN VARCHAR2
AS
  LRET VARCHAR2(500);
BEGIN
  SELECT PFNAME||decode(pfprice,null,'','[')||tools.fformatnum(pfprice,2)||decode(pfprice,null,'',']')
  INTO LRET
  FROM PRICEFRAME
  WHERE PFID = P_PFID;
  RETURN LRET;
EXCEPTION WHEN OTHERS THEN
  RETURN P_PFID;
END;
/

