CREATE OR REPLACE FUNCTION HRBZLS."FGETMISAVING_TYPE"
   (pbatch IN VARCHAR2,RLMRID IN VARCHAR2, P_TYPE IN VARCHAR2)
   RETURN NUMBER
AS
   LRET   NUMBER;
   LRET1   NUMBER;
   LRET2   NUMBER;
   VCOUNT NUMBER;

BEGIN

    IF P_TYPE = '1' THEN
          LRET :=   10;
    ELSIF P_TYPE = '2' THEN
          LRET :=   20;
    ELSIF P_TYPE = '3' THEN
          LRET :=   30;
    END IF;
    RETURN LRET;
EXCEPTION WHEN OTHERS THEN
   RETURN 0;
END fgetmisaving_type;
/

