CREATE OR REPLACE FUNCTION HRBZLS."FGETSYSFACELIST2" (P_MFNAME IN VARCHAR2)
 RETURN VARCHAR2
AS
 LRET VARCHAR2(100);
BEGIN
 SELECT  t.sflname
 INTO LRET
 FROM SYSFACELIST2  t
 WHERE t.sflid = P_MFNAME;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

