CREATE OR REPLACE FUNCTION HRBZLS."FGETSYSMANAFRAME" (P_SMFID IN VARCHAR2)
 RETURN VARCHAR2
AS
 LRET VARCHAR2(40);
BEGIN
 SELECT SMFNAME
 INTO LRET
 FROM SYSMANAFRAME
 WHERE SMFID = P_SMFID;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

