CREATE OR REPLACE FUNCTION HRBZLS."FGETSYSMANATYPE" (P_SMTID IN VARCHAR2)
 RETURN VARCHAR2
AS
 LRET CHAR(10);
BEGIN
 SELECT SMTNAME
 INTO LRET
 FROM SYSMANATYPE
 WHERE SMTID = P_SMTID;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

