CREATE OR REPLACE FUNCTION HRBZLS."FGETHSZBH"(P_MIID IN VARCHAR2) RETURN VARCHAR2 IS
  V_MIPRIID VARCHAR2(20);
BEGIN
  SELECT MIPRIID INTO V_MIPRIID FROM METERINFO T WHERE T.MIID = P_MIID;
  RETURN V_MIPRIID;
EXCEPTION
  WHEN OTHERS THEN
    RETURN P_MIID;
END;
/

