CREATE OR REPLACE FUNCTION HRBZLS."FGETMETERSORTFRAME" (P_MSFID IN VARCHAR2 )
 RETURN VARCHAR2
AS
 LRET VARCHAR2(20);
BEGIN
 SELECT MSFNAME
 INTO LRET
 FROM METERSORTFRAME
 WHERE MSFID = P_MSFID;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

