CREATE OR REPLACE FUNCTION HRBZLS."FGETPRICEFRAME_JH" (P_PFID IN VARCHAR2)
  RETURN VARCHAR2
AS
  LRET VARCHAR2(500);
BEGIN
  SELECT PFNAME
  INTO LRET
  FROM PRICEFRAME
  WHERE PFID = P_PFID;
  RETURN LRET;
EXCEPTION WHEN OTHERS THEN
  RETURN P_PFID;
END;
/

