CREATE OR REPLACE FUNCTION HRBZLS."FGETZHPRICE" (P_MCODE IN VARCHAR2) RETURN NUMBER
 AS
  P_PFPRICE NUMBER(12, 2);
BEGIN
  SELECT PFPRICE
  INTO P_PFPRICE
  FROM PRICEFRAME, METERINFO
 WHERE MIPFID = PFID
   AND MICODE = P_MCODE;
  RETURN P_PFPRICE;
EXCEPTION WHEN OTHERS THEN
  RETURN NULL;
END;
/

