CREATE OR REPLACE FUNCTION HRBZLS."FGETMETERBRAND" (P_MBID IN VARCHAR2 )
 RETURN VARCHAR2
AS
 LRET VARCHAR2(20);
BEGIN
 SELECT MBNAME
 INTO LRET
 FROM METERBRAND
 WHERE MBID = P_MBID;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

