CREATE OR REPLACE FUNCTION HRBZLS."FGETPAIDTRANS" (P_PTID IN VARCHAR2 )
 RETURN VARCHAR2
AS
 LRET VARCHAR2(20);
BEGIN
 SELECT PTNAME
 INTO LRET
 FROM PAIDTRANS
 WHERE PTID = P_PTID;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

