CREATE OR REPLACE FUNCTION HRBZLS."FGETITEMDJ" (P_RDPIID IN VARCHAR2,
                                      P_RLID   IN VARCHAR2) RETURN NUMBER IS
  V_RLID RECLIST.RLID%TYPE;
  V_DJ   RECDETAIL.RDYSDJ%TYPE;
BEGIN
  V_RLID := P_RLID;
  SELECT SUM(RD.RDYSDJ)
    INTO V_DJ
    FROM RECDETAIL RD
   WHERE RD.RDPIID = P_RDPIID
     AND RD.RDID = V_RLID
   GROUP BY RDID;
  RETURN V_DJ;
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;
/

