CREATE OR REPLACE FUNCTION HRBZLS."FGETFIRSTLETTER" (P_STRING IN VARCHAR2)
 RETURN VARCHAR2
AS
 TYPE CHARARRAY IS TABLE OF CHAR(1) INDEX BY BINARY_INTEGER;
 TYPE NUMARRAY IS TABLE OF NUMBER INDEX BY BINARY_INTEGER;
 LC_FIRSTLETTER CHARARRAY;
 LI_SECPOSVALUE NUMARRAY;
 I BINARY_INTEGER :=0;
 J BINARY_INTEGER :=0;
 --存放国标一级汉字不同读音的起始区位码对应读音
 LS_CH VARCHAR2(2); --临时单元
 LS_SECONDSECTABLE VARCHAR2(32767); --存放所有国标二级汉字读音
 LS_RETURNSTR VARCHAR2(60); --返回串
 --存放国标一级汉字不同读音的起始区位码
 LI_SECTORCODE NUMBER; --汉字区码
 LI_POSITIONCODE NUMBER; --汉字位码
 LI_SECPOSCODE NUMBER; --汉字区位码
 LI_OFFSET NUMBER; --二级字库偏移量
BEGIN
--COPY AND MODIFY FROM PUBLIC_FUNC.DBL:UF_GETFIRSTLETTER
--USED TO : 返回给定汉字串的首字母串,即声母串
--INPUT ARGUMENTS: : P_STRING - VARCHAR2 , 给定的汉字串
--RETURN VALUE : - STRING , 给定的汉字串的声母串,一律为小写
--NOTICE : 1. 此方法基于汉字的国标汉字库区位编码的有效性，
-- 不符合此编码的系统此函数无效！
-- 2. 若汉字串含有非汉字字符,如图形符号或ASCII码,
-- 则这些非汉字字符将保持不变.
--SAMPLE : SELECT FGETFIRSTLETTER("中华人民共和国") FROM DUAL;
-- : RESULT WILL BE : ZHRMGHG

--SCRIPTS:

--SET INITIAL VALUE
LI_SECPOSVALUE(1):=1601;
LI_SECPOSVALUE(2):=1637;
LI_SECPOSVALUE(3):=1833;
LI_SECPOSVALUE(4):=2078;
LI_SECPOSVALUE(5):=2274;
LI_SECPOSVALUE(6):=2302;
LI_SECPOSVALUE(7):=2433;
LI_SECPOSVALUE(8):=2594;
LI_SECPOSVALUE(9):=2787;
LI_SECPOSVALUE(10):=3106;
LI_SECPOSVALUE(11):=3212;
LI_SECPOSVALUE(12):=3472;
LI_SECPOSVALUE(13):=3635;
LI_SECPOSVALUE(14):=3722;
LI_SECPOSVALUE(15):=3730;
LI_SECPOSVALUE(16):=3858;
LI_SECPOSVALUE(17):=4027;
LI_SECPOSVALUE(18):=4086;
LI_SECPOSVALUE(19):=4390;
LI_SECPOSVALUE(20):=4558;
LI_SECPOSVALUE(21):=4684;
LI_SECPOSVALUE(22):=4925;
LI_SECPOSVALUE(23):=5249;

LC_FIRSTLETTER(1):='A';
LC_FIRSTLETTER(2):='B';
LC_FIRSTLETTER(3):='C';
LC_FIRSTLETTER(4):='D';
LC_FIRSTLETTER(5):='E';
LC_FIRSTLETTER(6):='F';
LC_FIRSTLETTER(7):='G';
LC_FIRSTLETTER(8):='H';
LC_FIRSTLETTER(9):='J';
LC_FIRSTLETTER(10):='K';
LC_FIRSTLETTER(11):='L';
LC_FIRSTLETTER(12):='M';
LC_FIRSTLETTER(13):='N';
LC_FIRSTLETTER(14):='O';
LC_FIRSTLETTER(15):='P';
LC_FIRSTLETTER(16):='Q';
LC_FIRSTLETTER(17):='R';
LC_FIRSTLETTER(18):='S';
LC_FIRSTLETTER(19):='T';
LC_FIRSTLETTER(20):='W';
LC_FIRSTLETTER(21):='X';
LC_FIRSTLETTER(22):='Y';
LC_FIRSTLETTER(23):='Z';

LS_SECONDSECTABLE:='CJWGNSPGCGNE[Y[BTYYZDXYKYGT[JNNJQMBSGZSCYJSYY[PGKBZGY[YWJKGKLJYWKPJQHY[W[DZLSGMRYPYWWCCKZNKYYGTTNJJNYKKZYTCJNMCYLQLYPYQFQRPZSLWBTGKJFYXJWZLTBNCXJJJJTXDTTSQZYCDXXHGCK[PHFFSS[YBGXLPPBYLL[HLXS[ZM[JHSOJNGHDZQYKLGJHSGQZHXQGKEZZWYSCSCJXYEYXADZPMDSSMZJZQJYZC[J[WQJBYZPXGZNZCPWHKXHQKMWFBPBYDTJZZKQHYLYGXFPTYJYYZPSZLFCHMQSHGMXXSXJ[[DCSBBQBEFSJYHXWGZKPYLQBGLDLCCTNMAYDDKSSNGYCSGXLYZAYBNPTSDKDYLHGYMYLCXPY[JNDQJWXQXFYYFJLEJPZRXCCQWQQSBNKYMGPLBMJRQCFLNYMYQMSQYRBCJTHZTQFRXQHXMJJCJLXQGJMSHZKBSWYEMYLTXFSY
DSWLYCJQXSJNQBSCTYHBFTDCYZDJWYGHQFRXWCKQKXEBPTLPXJZSRMEBWHJLBJSLYYSMDXLCLQKXLHXJRZJMFQHXHWYWSBHTRXXGLHQHFNM[YKLDYXZPYLGG[MTCFPAJJZYLJTYANJGBJPLQGDZYQYAXBKYSECJSZNSLYZHSXLZCGHPXZHZNYTDSBCJKDLZAYFMYDLEBBGQYZKXGLDNDNYSKJSHDLYXBCGHXYPKDJMMZNGMMCLGWZSZXZJFZNMLZZTHCSYDBDLLSCDDNLKJYKJSYCJLKWHQASDKNHCSGANHDAASHTCPLCPQYBSDMPJLPZJOQLCDHJJYSPRCHN[NNLHLYYQYHWZPTCZGWWMZFFJQQQQYXACLBHKDJXDGMMYDJXZLLSYGXGKJRYWZWYCLZMSSJZLDBYD[FCXYHLXCHYZJQ[[QAGMNYXPFRKSSBJLYXYSYGLNSCMHZWWMNZJJLXXHCHSY[[TTXRYCYXBYHCSMXJSZNPWGPXXTAYBGAJCXL
Y[DCCWZOCWKCCSBNHCPDYZNFCYYTYCKXKYBSQKKYTQQXFCWCHCYKELZQBSQYJQCCLMTHSYWHMKTLKJLYCXWHEQQHTQH[PQ[QSCFYMNDMGBWHWLGSLLYSDLMLXPTHMJHWLJZYHZJXHTXJLHXRSWLWZJCBXMHZQXSDZPMGFCSGLSXYMJSHXPJXWMYQKSMYPLRTHBXFTPMHYXLCHLHLZYLXGSSSSTCLSLDCLRPBHZHXYYFHB[GDMYCNQQWLQHJJ[YWJZYEJJDHPBLQXTQKWHLCHQXAGTLXLJXMSL[HTZKZJECXJCJNMFBY[SFYWYBJZGNYSDZSQYRSLJPCLPWXSDWEJBJCBCNAYTWGMPAPCLYQPCLZXSBNMSGGFNZJJBZSFZYNDXHPLQKZCZWALSBCCJX[YZGWKYPSGXFZFCDKHJGXDLQFSGDSLQWZKXTMHSBGZMJZRGLYJBPMLMSXLZJQQHZYJCZYDJWBMYKLDDPMJEGXYHYLXHLQYQHKYCWCJMYYXNAT
JHYCCXZPCQLBZWWYTWBQCMLPMYRJCCCXFPZNZZLJPLXXYZTZLGDLDCKLYRZZGQTGJHHGJLJAXFGFJZSLCFDQZLCLGJDJCSNZLLJPJQDCCLCJXMYZFTSXGCGSBRZXJQQCTZHGYQTJQQLZXJYLYLBCYAMCSTYLPDJBYREGKLZYZHLYSZQLZNWCZCLLWJQJJJKDGJZOLBBZPPGLGHTGZXYGHZMYCNQSYCYHBHGXKAMTXYXNBSKYZZGJZLQJDFCJXDYGJQJJPMGWGJJJPKQSBGBMMCJSSCLPQPDXCDYYKY[CJDDYYGYWRHJRTGZNYQLDKLJSZZGZQZJGDYKSHPZMTLCPWNJAFYZDJCNMWESCYGLBTZCGMSSLLYXQSXSBSJSBBSGGHFJLYPMZJNLYYWDQSHZXTYYWHMZYHYWDBXBTLMSYYYFSXJC[DXXLHJHF[SXZQHFZMZCZTQCXZXRTTDJHNNY
ZQQMNQDMMG[YDXMJGDHCDYZBFFALLZTDLTFXMXQZDNGWQDBDCZJDXBZGSQQDDJCMBKZFFXMKDMDSYYSZCMLJDSYNSBRSKMKMPCKLGDBQTFZSWTFGGLYPLLJZHGJ[GYPZLTCSMCNBTJBQFKTHBYZGKPBBYMTDSSXTBNPDKLEYCJNYDDYKZDDHQHSDZSCTARLLTKZLGECLLKJLQJAQNBDKKGHPJTZQKSECSHALQFMMGJNLYJBBTMLYZXDCJPLDLPCQDHZYCBZSCZBZMSLJFLKRZJSNFRGJHXPDHYJYBZGDLQCSEZGXLBLGYXTWMABCHECMWYJYZLLJJYHLG[DJLSLYGKDZPZXJYYZLWCXSZFGWYYDLYHCLJSCMBJHBLYZLYCBLYDPDQYSXQZBYTDKYXJY[CNRJMPDJGKLCLJBCTBJDDBBLBLCZQRPPXJCJLZCSHLTOLJNMDDDLNGKAQHQHJGYKHEZNMSHRP[QQJCHGMFPRXHJGDYCHGHLYRZQLCYQJNZS
QTKQJYMSZSWLCFQQQXYFGGYPTQWLMCRNFKKFSYYLQBMQAMMMYXCTPSHCPTXXZZSMPHPSHMCLMLDQFYQXSZYYDYJZZHQPDSZGLSTJBCKBXYQZJSGPSXQZQZRQTBDKYXZKHHGFLBCSMDLDGDZDBLZYYCXNNCSYBZBFGLZZXSWMSCCMQNJQSBDQSJTXXMBLTXZCLZSHZCXRQJGJYLXZFJPHYMZQQYDFQJJLZZNZJCDGZYGCTXMZYSCTLKPHTXHTLBJXJLXSCDQXCBBTJFQZFSLTJBTKQBXXJJLJCHCZDBZJDCZJDCPRNPQCJPFCZLCLZXZDMXMPHJSGZGSZZQLYLWTJPFSYASMCJBTZKYCWMYTCSJJLJCQLWZMALBXYFBPNLSFHTGJWEJJXXGLLJSTGSHJQLZFKCGNNNSZFDEQFHBSAQTGYLBXMMYGSZLDYDQMJJRGBJTKGDHGKBLQKBDMBYLXWCXYTTYBKMRTJZXQJBHLMHMJJZMQASLDCYXYQDLQCAFY
WYXQHZ.';

--GET IT !
LS_RETURNSTR := '';
I:=1;
LOOP
EXIT WHEN I>LENGTH(P_STRING); --依次处理P_STRING中每个字符
 LS_CH:=SUBSTR(P_STRING , I , 1);
 IF ASCII(LS_CH)<128 THEN -- 非汉字
 LS_RETURNSTR := LS_RETURNSTR||LS_CH; -- 不变
 ELSE -- 是汉字
 LS_CH := SUBSTR(P_STRING , I , 1); -- 取出此汉字
 LI_SECTORCODE := ASCII(SUBSTRB(LS_CH, 1 ,1)) - 160; --区码
 LI_POSITIONCODE := ASCII(SUBSTRB(LS_CH, 2 ,1)) - 160; --位码
 LI_SECPOSCODE := LI_SECTORCODE*100 + LI_POSITIONCODE; -- 区位码
 IF LI_SECPOSCODE>1600 AND LI_SECPOSCODE<5590 THEN -- 第一个字符
 J:=23;
 LOOP
 EXIT WHEN J<1; -- 找声母
 IF LI_SECPOSCODE>=TO_NUMBER(LI_SECPOSVALUE(J)) THEN
 LS_RETURNSTR := LS_RETURNSTR||LC_FIRSTLETTER(J);
 EXIT;
 END IF;
 J := J - 1;
 END LOOP;
 ELSE -- 第一个字符
 LI_OFFSET := (LI_SECTORCODE - 56 ) *94 + LI_POSITIONCODE - 1; -- 计算偏移量
 IF LI_OFFSET>=0 AND LI_OFFSET<=3007 THEN --二区汉字
 LS_RETURNSTR := LS_RETURNSTR||SUBSTR(LS_SECONDSECTABLE, LI_OFFSET , 1); --取出此字声母
 END IF;
 END IF;
 --I := I+1; -- 指向下一个汉字
 END IF;
 I:=I+1;
END LOOP; -- 处理完毕

--RETURN RESULT
RETURN(LOWER( LS_RETURNSTR )); --返回 P_STRING 的声母串
END FGETFIRSTLETTER;
/

