CREATE OR REPLACE FUNCTION HRBZLS."FGETMETERRTID" (P_SRTID IN VARCHAR2 )
 RETURN VARCHAR2
AS
 LRET VARCHAR2(20);
BEGIN
 SELECT SRTNAME
 INTO LRET
 FROM sysreadtype
 WHERE SRTID = P_SRTID;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

