CREATE OR REPLACE FUNCTION HRBZLS."FGETMETERFACE" (P_MFID IN VARCHAR2 )
 RETURN VARCHAR2
AS
 LRET VARCHAR2(20);
BEGIN
 SELECT MFNAME
 INTO LRET
 FROM METERFACE
 WHERE MFID = P_MFID;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

