CREATE OR REPLACE FUNCTION HRBZLS."FGETMACHINETYPE" (P_MTID IN VARCHAR2)
 RETURN VARCHAR2
AS
 LRET CHAR(60);
BEGIN
 SELECT MTNAME
 INTO LRET
 FROM MACHINETYPE
 WHERE MTID = P_MTID;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

