CREATE OR REPLACE FUNCTION HRBZLS."FGETBFRCYC" (P_BFID IN VARCHAR2)
 RETURN number
AS
 LRET number(2);
BEGIN
 SELECT BFRCYC
 INTO LRET
 FROM BOOKFRAME
 WHERE BFID = P_BFID;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN 0;
END;
/

