CREATE OR REPLACE FUNCTION HRBZLS."FGETMCODE" (P_MIID IN VARCHAR2)
 RETURN VARCHAR2
AS
 result varchar2(10);
BEGIN
 SELECT micode
 INTO result
 FROM METERINFO
 WHERE MIID = P_MIID;

 return result;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

