CREATE OR REPLACE FUNCTION HRBZLS."FGETPBSYSMANA" RETURN VARCHAR2
IS
 ret VARCHAR2(10);
BEGIN
SELECT fsysmanalbbm(fgetpbdept,'1') INTO ret FROM dual;
return ret;
EXCEPTION
   WHEN OTHERS THEN
        RETURN NULL;
END;
/

