CREATE OR REPLACE FUNCTION HRBZLS."FGETRECLIST" (P_rlid IN VARCHAR2,P_TYPE IN VARCHAR2 )
 RETURN VARCHAR2
AS
 rl reclist%ROWTYPE;
BEGIN
 SELECT *
 INTO rl
 FROM reclist
 WHERE rlid = P_rlid;
 IF P_TYPE='RLTRANS' THEN
    RETURN rl.RLTRANS;
 END IF;
 IF P_TYPE='RLPAIDFLAG' THEN
    RETURN rl.RLPAIDFLAG;
 END IF;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

