CREATE OR REPLACE FUNCTION HRBZLS."FGETDUALPARA1" (P_funpara IN VARCHAR2)
  RETURN VARCHAR2 AS
  V_COUNT NUMBER(10);
BEGIN
  SELECT COUNT(*) INTO V_COUNT from  METERINFO T WHERE T.MICODE=P_funpara;
  IF V_COUNT>0 THEN
    return 'N,有用户';
  ELSE
    return 'N,不通过';
  END IF;
EXCEPTION
  WHEN OTHERS THEN
   return  'N,异常';
END;
/

