CREATE OR REPLACE FUNCTION HRBZLS.FGETOPERMETHODDATE(VOAID IN VARCHAR2,
                                              VFID  IN VARCHAR2,
                                              VMID  IN VARCHAR2)
  RETURN DATE AS
  LDATE DATE;
BEGIN
  SELECT ORFMEXPIRYDATE
    INTO LDATE
    FROM OPERACCNTRFMETHOD_EX
   WHERE ORFMRID = VOAID
     AND ORFMFID = VFID
     AND ORFMETHOD = VMID;
  RETURN LDATE;
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;
/

