CREATE OR REPLACE FUNCTION HRBZLS."FGETCUSTINFO" (P_CIID IN VARCHAR2,P_TYPE IN VARCHAR2 )
 RETURN VARCHAR2
AS
 CI CUSTINFO%ROWTYPE;
BEGIN
 SELECT *
 INTO CI
 FROM CUSTINFO
 WHERE CIID = P_CIID;
 IF P_TYPE='CINAME' THEN
    RETURN CI.CINAME;
 END IF;
  IF P_TYPE='CINAME2' THEN
    RETURN CI.CINAME2;
 END IF;
  IF P_TYPE='CIADR' THEN
    RETURN CI.CIADR;
 END IF;
  IF P_TYPE='CISTATUS' THEN
    RETURN CI.CISTATUS;
 END IF;

EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

