CREATE OR REPLACE FUNCTION HRBZLS."FGETSYSMETERSTATUS" (P_SMSID IN VARCHAR2 )
 RETURN VARCHAR2
AS
 LRET VARCHAR2(20);
BEGIN
 SELECT SMSNAME
 INTO LRET
 FROM SYSMETERSTATUS
 WHERE SMSID = P_SMSID;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

