CREATE OR REPLACE FUNCTION HRBZLS."FGETMIFACE2"(P_MFID IN VARCHAR2)
  RETURN VARCHAR2 AS
  LRET VARCHAR2(20);
BEGIN
  SELECT T.SFLNAME INTO LRET FROM SYSFACELIST2 T WHERE SFLID = P_MFID;
  RETURN LRET;
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;
/

