CREATE OR REPLACE FUNCTION HRBZLS.FGETRFMETHODDATE(VRID IN VARCHAR2,
                                            VFID IN VARCHAR2,
                                            VMID IN VARCHAR2) RETURN DATE AS
  LDATE DATE;
BEGIN
  SELECT ORFMEXPIRYDATE
    INTO LDATE
    FROM OPERRFMETHOD_EX
   WHERE ORFMRID = VRID
     AND ORFMFID = VFID
     AND ORFMETHOD = VMID;
  RETURN LDATE;
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;
/

