CREATE OR REPLACE FUNCTION HRBZLS."FGETOPPARA" (P_OAID IN VARCHAR2,P_TYPE IN VARCHAR2 )
 RETURN VARCHAR2
AS
 LRET VARCHAR2(4000);
BEGIN
 SELECT OAPVALUE
 INTO LRET
 FROM OPERACCNTPARA
 WHERE OAPOAID = P_OAID AND OAPTYPE = P_TYPE AND OAPFLAG='Y';
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

