CREATE OR REPLACE FUNCTION HRBZLS.FGETPRINTLOG(P_FID IN VARCHAR2) RETURN NUMBER AS
  RET  NUMBER(10);
  RET1 NUMBER(10);
  RET2 NUMBER(10);
BEGIN
  --实收开票
  SELECT COUNT(*)
    INTO RET1
    FROM PRINTLOG
   WHERE FID = P_FID
     AND FTYPE = 'P';
  --应收开票
  SELECT COUNT(*)
    INTO RET2
    FROM PRINTLOG
   WHERE FID = P_FID
     AND FTYPE = 'L';
  RET := NVL(RET1, 0) + NVL(RET2, 0);
  RETURN RET;
EXCEPTION
  WHEN OTHERS THEN
    RETURN 0;
END;
/

