CREATE OR REPLACE FUNCTION HRBZLS."FGETMETERMODEL" (P_MMID IN VARCHAR2 )
 RETURN VARCHAR2
AS
 LRET VARCHAR2(20);
BEGIN
 SELECT MMNAME
 INTO LRET
 FROM METERMODEL
 WHERE MMID = P_MMID;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

