CREATE OR REPLACE FUNCTION HRBZLS."FGETMETERFACE2" (P_MFNAME IN VARCHAR2)
 RETURN VARCHAR2
AS
 LRET VARCHAR2(2);
BEGIN
 SELECT MFID
 INTO LRET
 FROM METERFACE
 WHERE MFNAME = P_MFNAME;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

