CREATE OR REPLACE FUNCTION HRBZLS."FGETBOOKFRAMESMFID" (P_SMFID IN VARCHAR2,P_BFID IN VARCHAR2)
 RETURN VARCHAR2
AS
 LRET VARCHAR2(60);
BEGIN
 SELECT BFNAME
 INTO LRET
 FROM BOOKFRAME
 WHERE BFID = P_BFID AND BFSMFID=P_SMFID ;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

