CREATE OR REPLACE FUNCTION HRBZLS."FGETZWDATE" (P_RAID IN VARCHAR2 )
 RETURN DATE
AS
 LRET DATE;
BEGIN
 SELECT PDATE
 INTO LRET
 FROM PAYMENT ,PAIDLIST
 WHERE PAYMENT.PID = PAIDLIST.PLPID
 AND  PAYMENT.pcd='DE'
 AND PAIDLIST.PLRLID=P_RAID;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

