CREATE OR REPLACE FUNCTION HRBZLS."FGETSYSCYCHEAD" (P_SCHID IN VARCHAR2 )
 RETURN VARCHAR2
AS
 LRET VARCHAR2(10);
BEGIN
 SELECT SCHNAME
 INTO LRET
 FROM SYSCYCHEAD
 WHERE SCHID = P_SCHID;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

