CREATE OR REPLACE FUNCTION HRBZLS."FGETSYSFACELIST4" (P_MFNAME IN VARCHAR2)
 RETURN VARCHAR2
AS
 LRET VARCHAR2(20);
BEGIN
 SELECT  t.sflname
 INTO LRET
 FROM SYSFACELIST4  t
 WHERE t.sflid = P_MFNAME;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

