CREATE OR REPLACE PROCEDURE HRBZLS."INFOMSG" (MSG IN VARCHAR2) AS
  slen PLS_INTEGER;
  SPOS PLS_INTEGER;
BEGIN
   insert into info_msg(MIID) values(SUBSTR(MSG,SPOS,4000));
   commit;
   slen:=length(MSG);
   SPOS:=1;
   WHILE SLEN>0 LOOP
     DBMS_OUTPUT.PUT_LINE(SUBSTR(MSG,SPOS,200));
     SPOS:=SPOS+200;
     SLEN:=SLEN-200;
   END LOOP;
END;
/

