CREATE OR REPLACE TRIGGER HRBZLS."tbi_bs_modi_log" BEFORE INSERT
ON bs_modi_log FOR EACH ROW

BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT FGETSEQUENCE('bs_modi_log') INTO :NEW.ID FROM DUAL;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

