CREATE OR REPLACE TRIGGER HRBZLS."TBI_METERSTORE_LOG" BEFORE INSERT
ON ST_METERSTORE_LOG FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SEQ_ST_METERSTORE_LOG.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

