CREATE OR REPLACE TRIGGER HRBZLS."TDA_PRICEMULTIDETAIL" AFTER DELETE
ON PRICEMULTIDETAIL FOR EACH ROW
BEGIN
  if nvl(fsyspara('data'),'N')='Y' then
     return;
  end if;
    UPDATE METERINFO SET MIIFMP='N' WHERE MICID=:OLD.PMDCID AND MIID=:OLD.PMDMID;
EXCEPTION WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20006,'É¾³ý');
END;
/

