CREATE OR REPLACE TRIGGER HRBZLS."TIB_DISTRICTINFO"
  BEFORE INSERT ON DISTRICTINFO
  FOR EACH ROW
DECLARE
BEGIN
  IF NVL(FSYSPARA('data'), 'N') = 'Y' THEN
    RETURN;
  END IF;
  IF :NEW.DIID IS NULL THEN
    SELECT 'XQ'||TO_CHAR(SEQ_DISTRICTINFO.NEXTVAL,'fm00000') INTO :NEW.DIID FROM DUAL;
  END IF;
END TIB_DISTRICTINFO;
/

