CREATE OR REPLACE TRIGGER HRBZLS."TIB_STREETMANAGE"
  BEFORE INSERT ON STREETMANAGE
  FOR EACH ROW
DECLARE
BEGIN
  IF NVL(FSYSPARA('data'), 'N') = 'Y' THEN
    RETURN;
  END IF;
  IF :NEW.STMID IS NULL THEN
    SELECT 'JD'||TO_CHAR(seq_streetmanage.nextval,'fm00000') INTO :NEW.STMID FROM DUAL;
  END IF;
END TIB_STREETMANAGE;
/

