CREATE OR REPLACE TRIGGER HRBZLS."TR_OPERROLEFUNC_AFTER_DELETE" AFTER DELETE
  ON OPERROLEFUNC
  FOR EACH ROW

BEGIN
  if nvl(fsyspara('data'),'N')='Y' then
     return;
  end if;
  DELETE FROM OPERRFMETHOD
   WHERE ORFMRID=:OLD.ORFRID AND ORFMFID = :OLD.ORFFID;
END;
/

