CREATE OR REPLACE TRIGGER HRBZLS."TRG_DA_INVSTOCK" AFTER DELETE
ON INVSTOCK FOR EACH ROW
BEGIN
  IF NVL(FSYSPARA('data'), 'N') = 'Y' THEN
    RETURN;
  END IF;
  DELETE INVSTOCKDETAIL T WHERE T.IDID = :OLD.ISID;
  /*    DELETE inv_info iv
  where iv.isid=:old.Isid;*/
END;
/

