CREATE OR REPLACE TRIGGER HRBZLS."TUA_RPT_HRBZLS_RLCHARGE"
  AFTER UPDATE OF RLIFSTORE ON RPT_HRBZLS_RLCHARGE
  FOR EACH ROW
DECLARE

BEGIN
  IF (UPDATING('RLIFSTORE') AND :OLD.RLIFSTORE != :NEW.RLIFSTORE) THEN
    UPDATE RPT_HRBZLS_RLCHARGENEW
       SET RLIFSTORE = :NEW.RLIFSTORE
     WHERE RLSMFID = :NEW.RLSMFID
       AND RLMONTH = :NEW.RLMONTH;
  END IF;
END;
/

