CREATE OR REPLACE TRIGGER HRBZLS."TUA_BILLMAIN"
  AFTER UPDATE OF BMID, BMSTATUS, BMNAME, BMTYPE, BMUSEROBJECT, BMFLAG2 ON BILLMAIN
  FOR EACH ROW
DECLARE

BEGIN
  IF (UPDATING('BMID') AND :OLD.BMID != :NEW.BMID) THEN
    UPDATE BILLMAIN_EX
       SET BMID = :NEW.BMID
     WHERE BMID = :OLD.BMID
       AND BMTYPE = :OLD.BMTYPE;
  END IF;

  IF (UPDATING('BMSTATUS') AND :OLD.BMSTATUS != :NEW.BMSTATUS) THEN
    UPDATE BILLMAIN_EX
       SET BMSTATUS = :NEW.BMSTATUS
     WHERE BMID = :OLD.BMID
       AND BMTYPE = :OLD.BMTYPE;
  END IF;

  IF (UPDATING('BMNAME') AND :OLD.BMNAME != :NEW.BMNAME) THEN
    UPDATE BILLMAIN_EX
       SET BMNAME = :NEW.BMNAME
     WHERE BMID = :OLD.BMID
       AND BMTYPE = :OLD.BMTYPE;
  END IF;

  IF (UPDATING('BMTYPE') AND :OLD.BMTYPE != :NEW.BMTYPE) THEN
    UPDATE BILLMAIN_EX
       SET BMTYPE = :NEW.BMTYPE
     WHERE BMID = :OLD.BMID
       AND BMTYPE = :OLD.BMTYPE;
  END IF;

  IF (UPDATING('BMUSEROBJECT') AND :OLD.BMUSEROBJECT != :NEW.BMUSEROBJECT) THEN
    UPDATE BILLMAIN_EX
       SET BMUSEROBJECT = :NEW.BMUSEROBJECT
     WHERE BMID = :OLD.BMID
       AND BMTYPE = :OLD.BMTYPE;
  END IF;

  IF (UPDATING('BMFLAG2') AND :OLD.BMFLAG2 != :NEW.BMFLAG2) THEN
    UPDATE BILLMAIN_EX
       SET BMFLOWID = :NEW.BMFLAG2
     WHERE BMID = :OLD.BMID
       AND BMTYPE = :OLD.BMTYPE;
  END IF;

END;
/

