CREATE OR REPLACE FORCE VIEW HRBZLS.V_ZP AS
(SELECT  CQ."CHEQUEID",CQ."ENTERINGTIME",CQ."PAYERNAME",CQ."PAYERTEL",CQ."CHEQUETYPE",CQ."CHEQUEMONEY",CQ."CHARGELOCATION",CQ."CHARGENAME",CQ."CHARGETIME",CQ."CHEQUECODE",CQ."CHEQUENAME",CQ."CHEQUEBANKNAME",CQ."CHEQUECHARGERID",CQ."CHEQUEMEMO",PMC."PCID",PMC."PCBATCH",PMC."PCCHEQUEID",PMC."PCCHEQUEMONEY",PMC."PCCASH"
FROM CHEQUE CQ,
     paymentcheque PMC
WHERE CQ.CHEQUEID=PMC.PCCHEQUEID
);

