CREATE OR REPLACE FORCE VIEW HRBZLS.VIEW_KPI_DEFINE AS
SELECT "KT_ID","KT_NAME","KT_PERIOD","ISACTIVE","KT_DATASOURCE","WARNING_UPPER","WARNING_LOWER","KT_SUB","KT_TYPE","KT_DISP","REMARK","WHERE_CAUSE" FROM kpi_define;

