CREATE OR REPLACE FORCE VIEW HRBZLS.VIEW_MR_BDMONTH AS
SELECT rank() over£¨partition by MRMID order by MRMONTH desc) mrnum, MRMONTH,MRMID,mrsl
  FROM METERREADHIS
 WHERE MRREADOK = 'Y'
   AND MRIFTRANS = 'N';

