create or replace force view hrbzls.view_recdetailall as
select "RDID","RDPMDID","RDPIID","RDPFID","RDPSCID","RDCLASS","RDYSDJ","RDYSSL","RDYSJE","RDDJ","RDSL","RDJE","RDADJDJ","RDADJSL","RDADJJE","RDMETHOD","RDPAIDFLAG","RDPAIDDATE","RDPAIDMONTH","RDPAIDPER","RDPMDSCALE","RDILID","RDZNJ","RDMEMO","RDMSMFID","RDMONTH","RDMID","RDPMDTYPE","RDPMDCOLUMN1","RDPMDCOLUMN2","RDPMDCOLUMN3" from recdetail
union
select "RDID","RDPMDID","RDPIID","RDPFID","RDPSCID","RDCLASS","RDYSDJ","RDYSSL","RDYSJE","RDDJ","RDSL","RDJE","RDADJDJ","RDADJSL","RDADJJE","RDMETHOD","RDPAIDFLAG","RDPAIDDATE","RDPAIDMONTH","RDPAIDPER","RDPMDSCALE","RDILID","RDZNJ","RDMEMO","RDMSMFID","RDMONTH","RDMID","RDPMDTYPE","RDPMDCOLUMN1","RDPMDCOLUMN2","RDPMDCOLUMN3" from recdetailhis;

