CREATE OR REPLACE PROCEDURE HRBZLS."无流程单据权限初始化" IS
  CURSOR C_FD IS
    SELECT * FROM FLOW_DEFINE;
  V_FD FLOW_DEFINE%ROWTYPE;
  V_FO FLOW_OPER_DEFINE%ROWTYPE;
BEGIN
  DELETE FLOW_OPER_DEFINE;
  OPEN C_FD;
  LOOP
    FETCH C_FD
      INTO V_FD;
    EXIT WHEN C_FD%NOTFOUND OR C_FD%NOTFOUND IS NULL;
    INSERT INTO FLOW_OPER_DEFINE
      SELECT V_FD.FID, V_FD.FNO, OAID, NULL FROM OPERACCNT;
  END LOOP;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
END;
/

