CREATE OR REPLACE FUNCTION "FGETCUSTNAME" (P_CIID IN VARCHAR2 )
 RETURN VARCHAR2
AS
 LRET VARCHAR2(60);
BEGIN
 SELECT CINAME
 INTO LRET
 FROM BS_CUSTINFO
 WHERE CIID = P_CIID;
 RETURN LRET;
EXCEPTION WHEN OTHERS THEN
 RETURN NULL;
END;
/

